[package]
name = "bidirectional_p2p_chat"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.31"
tokio = { version = "1.44.0", features = ["full"] }

[[bin]]
name = "peer"
path = "src/bin/peer.rs"